### ISSUE TITLE
Use channel BOM instead of manifest.xml

### ISSUE THREAD

**Issue by spyrkob** [spyrkob/prospero#30]

**Comment by spyrkob** [comment]
97d4ff0eac7446b5f658530abb4ff864f619e35f
e51bd2fcbffbed51559981ae7fedaf615680deda
baf8be06f0c1eefcca0abd0c318c1ba46b6c73bb

**Comment by wolfc** [comment]
This function should really be in wildfly-channel.

Note that a channel definition must not contain any repositories.
